version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - node-network

  app:
    build: app
    container_name: app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 30s docker-entrypoint.sh
    restart: always
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && app index.js"
    depends_on:
      - mysql
    networks:
      - node-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  mysql-data:
